### ISSUE TITLE
Speed of tagging via adding components vs changing data on existing components

### ISSUE THREAD

**Issue by Will-Carson** [reeseschultz/ReeseUnityDemos#18]
It seems like you're storing entity state via adding "tag" components to relevant entities: https://github.com/reeseschultz/ReeseUnityDemos/blob/master/Packages/com.reese.nav/Agent/NavAgentStatus.cs

According to [this thread](https://forum.unity.com/threads/flagging-for-filtering-better-to-add-remove-empty-component-or-poll-over-component-data-int.599200/) it's many orders of magnitudes faster to have a tag component that stores a status variable and is always attached to the relevant entity. In this case, you could add bools to all of those components, and then instead of looking for the components, check their status in a job and handle them however they should be handled. 

However it would make sense that adding/removing a tag component would be better if you're able to exclude an entity (or many entities) from a system over many frames, but I'm not sure at what point it's more performant to add/remove components vs changing a variable on a permanent component. Like I said I'm not sure, and I'm curious what your thoughts are.

**Comment by reeseschultz** [comment]
> However it would make sense that adding/removing a tag component would be better if you're able to exclude an entity (or many entities) from a system over many frames

I believe that was why I ended up tagging (in addition to improving readability and ease of interfacing with the nav code through custom user systems). Otherwise, each flag for each entity must be inspected for each concerned system roughly for each frame, which doesn't scale well as the number of nav agents grows. I'll grant you that if there aren't many nav agents, then the flags might be better. I guess flags would scale if the agents were batched, but I don't see the point in doing the work involved when everything already seems to scale fine.

Another concern I have is that the linked thread is extremely dated at this point. If I recall correctly in my reading up on ECS/Burst updates over many recent months, Unity has made strides improving performance regarding tags, but my memory is hazy. I believe there are comments in their changelogs confirming my vague suspicion that the tagging is probably okay in this context.

With all that said, if you want to refactor the nav package, please do. If you demonstrate a major performance boost by simply using the flags instead of tags, I'd be happy to accept your PR. Without somebody actually making the change and doing the comparison, we can't know for sure.

**Comment by reeseschultz** [comment]
@Rigormortis115, are you interested in submitting a PR, or can I close this issue?
