### ISSUE TITLE
Add terrain support

### ISSUE THREAD

**Issue by williamtsoi** [reeseschultz/ReeseUnityDemos#37]
Hi Reese, first of all thanks for this project.

**Is your feature request related to a problem? Please describe.**

I have tried to create a new demo scene with a simple terrain, to test this solution working with a terrain.
I then added the current NavSurfaceAuthoring script to a terrain, and have also included a TerrainColliderAuthoring script(not by me, but I think this is working as expected) to convert the terrain collider.
I then ran the scene and found that the performance is not what I expected when compared to the PerformanceDemo scene.

**Describe the solution you'd prefer:**

A drag and drop NavSurfaceAuthoring script which can be added to a Unity Terrain GameObject using Convert To Entity => Convert and Inject Game Object flow.

**Describe alternatives or workarounds you've considered:**

Maybe not using unity terrain.

**Additional context:**
Created a pull request with a new Demo Scene
https://github.com/reeseschultz/ReeseUnityDemos/pull/36

**Comment by reeseschultz** [comment]
Hi! I'm open to supporting terrain, with help.

The `NavPlanSystem` should theoretically be able to support non-flat surfaces already since it orchestrates [relevant third-party code here](https://github.com/reeseschultz/ReeseUnityDemos/tree/master/Packages/com.reese.nav/ThirdParty/PathUtils), but I haven't tested this yet. Based on the screenshots and code in the PR, my guess is that the `NavPlanSystem` is being provided destinations it fails to reach since they're being set along a flat surface, not specific destinations running along the terrain. I could be wrong or misunderstanding, but it looks the `TerrainDestinationSystem` assumes a flat surface. Unfortunately my planning system's "disgraceful" handling of unreachable destinations is related to #35, which I need to resolve soon.

Your PR looks pretty good; I think your approach makes sense. We can continue our discussion in the PR comments. Now, I'm super busy these next couple days, but I'll reach out to you afterward. Then I can test your PR and confirm my suspicions about what's going on. There's a good chance that more work will be needed beyond what I've already mentioned for us to get this feature done, due to how obstacle detection has been hacked into the `NavInterpolationSystem`, among other things. I certainly agree terrain support should be a thing and look forward to working with you on this.

**Comment by williamtsoi** [comment]
No probs, no rush :) I'm only going to be able to work on this once in a while too. Will continue further discussion on the PR as you suggested.

**Comment by reeseschultz** [comment]
Closing since 298cefd79d438cb860b39b9166511693d284ad82 has been merged!
