### ISSUE TITLE
Separation of Navigation Planning and Agent Navigation

### ISSUE THREAD

**Issue by williamtsoi** [reeseschultz/ReeseUnityDemos#51]
**Is the improvement related to a problem? Please describe.**

It would make my life easier if the navigation planning is split from the movement of the agent itself. This would be useful for scenarios where the agent does not represent a single entity which needs to be moved, but rather a holder of a path.

**Describe the solution you'd prefer:**

For the `NavPlanSystem` to tag the agent when it has successfully found a path instead of adding the `NavLerping` tag, then it would be possible to build our own systems to handle the path as required.

**Describe alternatives or workarounds you've considered:**

Not use and or disable the existing `NavPlanSystem`, and instead duplicate a version which will then add the tag as necessary. 

**Additional context:**

Example scenario: If there are 100 units in a squad, then instead of each squad member being an agent, the agent itself could be the squad entity which asks for the path (but does not have it's own movement), while the movement would then be handled by the individual units instead. It would then be up to the individual game/simulation on how it wants to handle when it has arrived at each waypoint etc. based on the squad member entities, and not use the included `NavInterpolationSystem`

**Comment by reeseschultz** [comment]
Sorry for the wait @williamtsoi, I've had a busy month.

I'll remedy this soon as discussed in Discord, but it may have to live on the `feat/demo-overhaul` branch for a while. That branch is kind of blocking everything else atm, since it's such a drastic set of changes.

**Comment by reeseschultz** [comment]
@williamtsoi with the latest version of nav, you should be able to change the `CustomLerp` property in `NavNeedsDestination` to `true`. If you do that, planning will be executed as usual, however when planning is done and lerping is possible, you can then check for existence of the `NavCustomLerping` component and manage the path buffer yourself in custom jobs. Since `NavLerping` is *not* added to agents in that case, the nav library will make no attempt to lerp them for you.

**Comment by reeseschultz** [comment]
Hope that helps! Sorry for the wait.
