### ISSUE TITLE
Runtime baking supported?

### ISSUE THREAD

**Issue by HollowGraphic** [reeseschultz/ReeseUnityDemos#54]
The NavMeshComponents package from Unity supports runtime baking, does this package make use of that?

**Comment by reeseschultz** [comment]
The nav package includes NavMeshComponents as a dependency, which is justified performance-wise because mostly people just use it for their authoring workflow. By inspecting the demos, you would find useful examples of this.

Since that's what's being used, runtime baking should work; it's just not multi-threaded. You'd just need to collect your `NavMeshSurfaces` and call `BuildNavMesh` on them from the main thread. If anything changes too substantially, of course you may remove an agent from a navigable area, and in that case you would need to resolve that situation with your user code.

**Comment by reeseschultz** [comment]
Oh, by the way, you'll notice all GameObjects with the `NavMeshSurface` component are injected as GameObjects in the demos for this reason. The point of my nav library is to maximize performance of navigation itself (to the extent that it does not impede usability), not the navigation mesh, since generally what incurs the greatest performance impact is the number of agents navigating simultaneously.

**Comment by reeseschultz** [comment]
Assuming the question has been answered well enough; closing.
