### ISSUE TITLE
Buffers utilizing too much stack data

### ISSUE THREAD

**Issue by albin-johansson** [reeseschultz/ReeseUnityDemos#64]
**Bug description:**

Unity will throw a bunch of exceptions if a game object has both `SpatialTriggerAuthoring` and `SpatialActivatorAuthoring` scripts attached to it.

**Bug reproduction:**

1. Open the "Stranded" demo scene
2. Add a `SpatialTriggerAuthoring` script to the player game object.
3. Run the scene
4. Press somewhere in the scene, to make the player character move. The error messages should now appear.

**Expected behavior:**

Entities should, according to the README at least, be able to be activators and triggers at the same time.
> It is perfectly fine for an object to be both a trigger and activator (even though it may belong to the same tag as itself, self-activation is not possible).

**Describe alternatives or workarounds you've considered:**

The first error message says `ArgumentException: System.InvalidOperationException: Entity archetype component data is too large...`. Maybe this could be solved by configuration some limit in the project, but I have not been able to identify any workarounds.

**Additional context:**

Here is the configuration of the authoring scripts, attached to the player game object.
![image](https://user-images.githubusercontent.com/23718844/111904322-a2e20f80-8a46-11eb-9f47-9876a7da2c2d.png)

This results in the following error messages.
![image](https://user-images.githubusercontent.com/23718844/111903825-4c73d180-8a44-11eb-9669-93e26e0041dc.png)

**Comment by albin-johansson** [comment]
After investigating this further, I think that I've managed to get it working in a scene of my own. However, I'm still unsure about why it doesn't work in the Stranded demo, I think that it might be because it results in some modification of entity state whilst some other system (or systems) are reading from said data, causing issues with data synchronization.

**Comment by reeseschultz** [comment]
The error message says that too much component data is being used per entity, because the buffers probably demand too much by default.

FYI, all buffers in the spatial package currently make said demand like so:

```csharp
[InternalBufferCapacity(10)]
```

At some point I was going to replace that magic number with something reasonable, which I neglected to do.

Anyway, my understanding is that the default limit on total component data is 16KB, which is completely reasonable and a not a problem in itself. It's a limit we want to respect, because we don't want to bogart the CPU's cache.

The ultimate solution is to force all these buffer allocations on the heap, which should have a negligible (if even noticeable) performance impact. This is achieved simply by specifying an internal buffer capacity of zero, like this:

```csharp
[InternalBufferCapacity(0)]
```
I could create a `SpatialConstants` class with one integer, being zero, that I could provide a comment on that would explain the situation. The navigation package already does something similar. But in fact, the defaults for its buffers are probably too great as well.

I'll patch this later today or tomorrow. For now, you can manually modify the code as I have for each buffer as a workaround. They're in `Packages/com.reese.spatial/Buffers`. That should solve the problem and prevent confusing issues for future users.
