### ISSUE TITLE
Conflict with unity.physics

### ISSUE THREAD

**Issue by 89trillion-wanglefan** [reeseschultz/ReeseUnityDemos#66]
I've been trying to use this navigation with an agent who has physics body on it. The problem is that I can only insert or delete an agent in the step physics world after the navLerpSystem, otherwise it will cost a ton of problems. Also agents will be launched to the sky if the frame cost more than 30 or 40 ms to calculate. when I tried to use physics velocity in navLerpSystem, any collision will launch the agent. 
So I wonder what's the reason? Maybe the nav system is still modifying the physics while unity.physics runs. Is there a way to fix this?

**Comment by reeseschultz** [comment]
At present, the navigation is not supported for physical agents. For now they are only parented to surfaces. Parenting and physics don't mix well. Naturally, I believe your issue would be resolved per the resolution of #43, so I would call it a duplicate. #43 is a much broader change than it may initially seem, though, and I haven't yet found time to resolve it.

As for the conflict preventing you from updating until after the `NavLerpSystem`, the navigation systems do in fact utilize physics; firstly to detect underlying surfaces, and secondly to avoid obstacles. The obstacle avoidance is likely the direct cause of the conflict you mentioned (which occurs in the `NavLerpSystem`). I consider it a hack that could probably be replaced with analysis, but even if the method were to stay the same, it's only raycasting and not modifying any physics state. So, really, it comes down to #65, but the reporters want me to add a sync point for something that really shouldn't need one.

The backlog of physics-related issues are more time-consuming than others to resolve, mainly because they're difficult to test. I have no way of knowing what the user may or may not do with physics, in addition to the fact that the nav agents themselves cannot yet be physical without inherent code changes. Someone on Discord made a fork where it works fine, but they ripped out the surface parenting code and stuff. Mainly I think they preserved only the `NavMeshQuerySystem`, `NavDestinationSystem`, `NavLerpSystem`, and `NavPlanSystem`, but of course their fork is private so I don't know. Generally speaking, I've observed that most aren't keen on sharing their code or publicly collaborating via PRs, because their concern only extends to their immediate needs being resolved. It's understandable, since people just want to make games and not tools.

Sorry for writing the textbook, I just wanted to establish why there continue to be issues with physics in case you or anyone else is curious.

**Comment by 89trillion-wanglefan** [comment]
Thanks for your response. I fixed the problem with insertion by the last comment of #65. now I can respawn a new physic agent in initialization. I'll also see to the parenting problem with physics, maybe it's a good idea to store this relation elsewhere?

**Comment by reeseschultz** [comment]
Please see https://github.com/reeseschultz/ReeseUnityDemos/issues/65#issuecomment-864041215.

**Edit:** Also, please see #67.
