### ISSUE TITLE
Fix closest position in SearchQuadrantNeighbors

### ISSUE THREAD

**Issue by ptbarnaby** [reeseschultz/ReeseUnityDemos#78]
closestDistance is initialised inside SearchQuadrantNeighbor, this means when scanning multiple quadrants the last quadrant containing agents is the one that overwrites closestQuadrantData even if a previous quadrant contained a closer point.

My suggested fix for this is to update the calling method (SearchQuadrantNeighbors) to initialise the closest distance as positive infinity, then pass it into each SearchQuadrantNeighbor() call by ref. You would then need to remove these two lines before the do-loop:

`closestQuadrantData = quadrantData;`

`var closestDistance = math.distance(pos, quadrantData.LocalToWorld.Position);`

As they overwrite any closer position found in a previous quadrant.

-----

Additionally you might consider calling SearchQuadrantNeighbor() for the diagonal positions too, as an agent in the corner of a quadrant will not test against an agent that is < 1 m in the diagonal quadrant (i.e. that shares one quadrant vertex)

**Comment by reeseschultz** [comment]
FYI, this won't result in any changes to the `path` package, just the associated demo scripts. The `nav` package, however, will be changed as well.

Also—I'm still working on a new releasing paradigm for this repo. I'll be using GitHub Actions + Node + TypeScript, which I decided to make available for any Unity project, because ultimately sharing the code will make everyone's life easier in the long-run. However, being able to handle the various permutations of prereleases is horrendous, so it'll take some time before the packages in this repo start getting released in the new way. I don't intend on putting the `path` package or the others on OpenUPM until that work is done.

**Comment by reeseschultz** [comment]
Closing per merge of #96; your suggested fix works perfectly, @ptbarnaby. Thanks!
