### ISSUE TITLE
Add flocking variables to hybrid nav agents

### ISSUE THREAD

**Issue by transcendtient** [reeseschultz/ReeseUnityDemos#81]
I don't see any properties for this in the description on OpenUPM. Are there any plans to add this feature?

NavAgent has an AgentAversionDistance initialization variable that sounds like local avoidance.

**Comment by reeseschultz** [comment]
The `NavAgentHybrid` does not have initialization variables for flocking, but it could! The only reason it doesn't (yet) is because I and the innumerable other possible contributors have not taken the time to prioritize this work. It's something that would naturally follow the inclusion of #80, because that demo would make it easier to visually inspect that the nav hybrid agents flock appropriately with the right settings. If this is something you want to work on, please let me know.

Otherwise, you'll have to wait for someone else to get around to it.

---

Also, as for project planning... that should all be happening on GitHub Issues, which is why I'm glad you brought this up. For this project specifically, I am skeptical of long-term planning via GitHub Projects (which I use extensively in proprietary/private projects). The reason being is *this* project must stay as reactive as possible to new developments in Unity DOTS, which could, for example, introduce an *official* navigation package at any time. What's more, the `Entities` package is experimental after all, so depend on it at your own peril. As of recent, Unity has not communicated their intentions for DOTS aside from vague and sporadic forum posts....

**Comment by reeseschultz** [comment]
Closing, see #99.
