### ISSUE TITLE
Can the Reese.Nav system not be used as a subscene?

### ISSUE THREAD

**Issue by zlxt2714** [reeseschultz/ReeseUnityDemos#90]
Can the Reese.Nav system not be used as a subscene?
Master, I need your help!
When I use the Reese.Nav system in the main scene, everything is OK. When I load it as a subscene, it cannot work . The error is reported as follows. How to solve this problem?

System.ArgumentException: The start location doesn't belong to any active NavMesh surface.
This Exception was thrown from a job compiled with Burst, which has limited exception support.
0x00007ff9a30c5389 (11e30ee153ffbc8a8f28b99f8105cbf) [unknown:0] UnityEngine.Experimental.AI.NavMeshQuery::UnityEngine.Experimental.AI.NavMeshQuery.BeginFindPath 
0x00007ff9a30c298e (11e30ee153ffbc8a8f28b99f8105cbf) [unknown:0] Reese.Nav.NavPlanSystem/Reese.Nav.NavPlanJob::Reese.Nav.NavPlanSystem.Reese.Nav.NavPlanJob.IterateEntities 
0x00007ff9a30c16b7 (11e30ee153ffbc8a8f28b99f8105cbf) [IJobChunk.cs:375] Unity.Entities.JobChunkExtensions.JobChunkProducer`1<Reese.Nav.NavPlanSystem.Reese.Nav.NavPlanJob>.ExecuteInternal 
0x00007ff9a30c1451 (11e30ee153ffbc8a8f28b99f8105cbf) 1B10956352FE8761
0x00007ff7645e5060 (Unity) ExecuteJob
0x00007ff7645e5315 (Unity) ExecuteJobCopyData
0x00007ff7645e5f5f (Unity) ForwardJobForEachToManaged
0x00007ff7645c9fdc (Unity) JobQueue::Exec
0x00007ff7645ca8ba (Unity) JobQueue::ExecuteJobFromHighPriorityStack
0x00007ff7645cc616 (Unity) JobQueue::ProcessJobs
0x00007ff7645d309f (Unity) JobQueue::WorkLoop
0x00007ff764be645e (Unity) Thread::RunThreadWrapper
0x00007ffa0b217034 (KERNEL32) BaseThreadInitThunk
0x00007ffa0b742651 (ntdll) RtlUserThreadStart

**Comment by reeseschultz** [comment]
Hello! The `Reese.Nav` package is incompatible with subscenes. The library's conception of surfaces is, at present, technically impossible to reconcile with subscenes due to how they are authored. I do not recommend using subscenes with `Reese.Nav`.

If you choose to use subscenes, I recommend `Reese.Path` instead, which, to my knowledge, should *not* have such incompatibilities, but, of course, you would be responsible for writing your own interpolation code. Thankfully, an example has already been provided in the demos.

I will *not* support subscenes with the nav package until Unity improves their developer experience. Please let me know if this helps clarify the issue.

**Comment by zlxt2714** [comment]
您的邮件，我收到了，谢谢。
